//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddAssetTable
    {
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PricePerItem { get; set; }
        public Nullable<long> TotalPrice { get; set; }
    }
}
